# Generated by Django 5.1 on 2024-08-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='publishers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('image', models.ImageField(upload_to='publisher/image')),
            ],
        ),
    ]
