# Generated by Django 5.1 on 2024-08-22 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='billboards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coordinates', models.TextField(max_length=5000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('locality', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('num_of_boards', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('publisher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.publishers')),
            ],
        ),
    ]
