# Generated by Django 5.1 on 2024-08-22 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='billboard_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='types/image')),
            ],
        ),
        migrations.AddField(
            model_name='billboards',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billboard.billboard_type'),
            preserve_default=False,
        ),
    ]
