# Generated by Django 5.1 on 2024-08-26 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0002_billboard_type_billboards_type'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='billxcomp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('billboard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billboard.billboards')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companies')),
            ],
        ),
    ]
