# Generated by Django 5.1.1 on 2024-09-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0005_alter_billboards_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='billxcomp',
            name='file',
            field=models.FileField(null=True, upload_to='billboard/file'),
        ),
    ]
