# Generated by Django 5.1.1 on 2024-09-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyauthtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
